### ISSUE TITLE
How about fit preview image into preview image area?

### ISSUE THREAD

**Issue by bscheshirwork** [zxbodya/yii2-gallery-manager#75]
This is some strange:

```css
.gallery-manager .photo img {
    width: 140px;
    height: auto;
}

.gallery-manager .image-preview {
    height: 88px;
    overflow: hidden;
}
```
```php
    /**
     * Widget preview height
     * @var int
     */
    public $previewHeight = 200;
    /**
     * Widget preview width
     * @var int
     */
    public $previewWidth = 200;
```
https://github.com/zxbodya/yii2-gallery-manager/blob/4a9ca72b36900195f34004926e593ed00cb91252/GalleryBehavior.php#L121-L127

![peek 2018-12-20 14-40](https://user-images.githubusercontent.com/5769211/50282934-638e7800-0465-11e9-8886-1149d09da588.gif)
